### ISSUE TITLE
[BUG] Advisers not showing up in the cover page

### ISSUE THREAD

**Issue by devzizu** [joaomlourenco/novathesis#255]
**Which version of the template are you using?**

Version 2021-11-18 [6.6.7]

**Do you use a cloud-based service?  Which one?**

Yes, Overleaf with the XeLateX compiler

**What went wrong?**

When adding two or more advisers they disappear from the cover page

**Instructions to Reproduce the Error**

1. Start from a "fresh" distribution of the template v6.6.7
2. Follow the steps from [Uminho Configuration](https://github.com/joaomlourenco/novathesis/wiki/Uminho-Configuration) for configuring the UM template
3. In Config/5_cover.tex, add two "\ntaddperson{adviser}..." from the comments examples.

They don't show in the cover page.

**Comment by b-pereira** [comment]
Do you mean the cover or the front-page?

**Comment by devzizu** [comment]
I mean the black and white page that has the "Work developed under the supervision of:" phrase.

**Comment by joaomlourenco** [comment]
The compilation is failing in my computer.  I'll check what's the problem.

**Comment by joaomlourenco** [comment]
I believe it's fixed now!  Just replace your "novathesis.cls" with the new one in the repo.
Please confirm that it works for you now.  Thanks.

**Comment by devzizu** [comment]
Yes, the advisers are working now!
Although, there is still one compilation error showing and I don't know if it's important.

![Screenshot from 2021-11-20 15-48-26](https://user-images.githubusercontent.com/47277541/142732621-e370aec1-2457-460f-a103-e85ac64df0c6.png)

Thank you for your time!

**Comment by joaomlourenco** [comment]
Please also update your "NOVAthesisFiles/Schools/uminho/univ-defaults.ldf" and tell me if the error persists.  Thanks.

**Comment by devzizu** [comment]
Yes, the error persists. I believe it already existed before the fix you provided for advisers.

**Comment by b-pereira** [comment]
> Yes, the error persists. I believe it already existed before the fix you provided for the "advisers problem".

I compiled directly from the repository in Linux with the Makefile with the latest commit. I'm going to check in Overleaf. Meanwhile, do this (if you have much): 

1. Make a backup from your files, namely,  “Bibliography”, “Chapters”, and “Config” (version A)
2. Download the latest version of the template (v6.6.7) — directly from the `main` branch as you did before (version B)
3. Replace the folders (in B) with your current versions (from A).

If you didn't changed that much, just download  the current version in the `main` branch.

**Comment by devzizu** [comment]
Cloned it from the main branch and added my folders, still shows the same error. What if i give you access to the project?

**Comment by b-pereira** [comment]
> I cloned it from the main branch and added my folders, still shows the same error. What if I give you access to the project?

That's really odd. Let me check on Overleaf.

**Comment by b-pereira** [comment]
> I cloned it from the main branch and added my folders, still shows the same error. What if I give you access to the project?

I checked on Overleaf. Everything is OK. If you want, you can send PM by Facebook https://www.facebook.com/pereirabruno05/
